In [ ]:
# Title: Basic NumPy Operations
# Description: Perform basic operations such as calculating the mean of the dataset.

In [1]:
import numpy as np

# Create a 1D NumPy array (dataset)
data = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", data)

# Calculate the mean of the 1D array
mean_value = np.mean(data)
print(f"\nThe mean of the 1D array is: {mean_value}")

# Create a 2D NumPy array (matrix)
matrix_data = np.array([[1, 2, 3],
                        [4, 5, 6]])
print("\n2D Array:\n", matrix_data)

# Calculate the mean of all elements in the 2D array
mean_all = np.mean(matrix_data)
print(f"Mean of all elements in the 2D array: {mean_all}")

# Calculate the mean along each column (axis=0) of the 2D array
mean_columns = np.mean(matrix_data, axis=0)
print(f"Mean along columns (axis=0): {mean_columns}")

# Calculate the mean along each row (axis=1) of the 2D array
mean_rows = np.mean(matrix_data, axis=1)
print(f"Mean along rows (axis=1): {mean_rows}")

1D Array:
 [1 2 3 4 5]

The mean of the 1D array is: 3.0

2D Array:
 [[1 2 3]
 [4 5 6]]
Mean of all elements in the 2D array: 3.5
Mean along columns (axis=0): [2.5 3.5 4.5]
Mean along rows (axis=1): [2. 5.]
